import { Injectable } from '@angular/core';
import { iTodos } from '../models/i-todos';

@Injectable({
  providedIn: 'root',
})
export class TodosService {
  todos: iTodos[] = [
    {
      id: 1,
      todo: 'Slay the dragon',
      completed: true,
      userId: 8,
    },
    {
      id: 2,
      todo: 'Retrieve the lost artifact',
      completed: false,
      userId: 12,
    },
    {
      id: 3,
      todo: 'Explore the haunted forest',
      completed: true,
      userId: 32,
    },
    {
      id: 4,
      todo: 'Defend the kingdom from invading orcs',
      completed: false,
      userId: 23,
    },
    {
      id: 5,
      todo: 'Find the legendary sword of power',
      completed: true,
      userId: 47,
    },
    {
      id: 6,
      todo: 'Seek out the wise wizard for guidance',
      completed: true,
      userId: 16,
    },
    {
      id: 7,
      todo: 'Rescue the kidnapped princess',
      completed: false,
      userId: 39,
    },
    {
      id: 8,
      todo: 'Uncover the ancient prophecy',
      completed: true,
      userId: 10,
    },
    {
      id: 9,
      todo: 'Conquer the dark dungeon',
      completed: false,
      userId: 28,
    },
    {
      id: 10,
      todo: 'Attend the gathering of wizards',
      completed: true,
      userId: 36,
    },
    {
      id: 11,
      todo: 'Master the art of spellcasting',
      completed: false,
      userId: 13,
    },
    {
      id: 12,
      todo: 'Defeat the evil sorcerer',
      completed: false,
      userId: 2,
    },
    {
      id: 13,
      todo: 'Discover the hidden treasure',
      completed: true,
      userId: 24,
    },
    {
      id: 14,
      todo: 'Train with the legendary warriors',
      completed: false,
      userId: 49,
    },
    {
      id: 15,
      todo: 'Navigate through the labyrinthine maze',
      completed: true,
      userId: 7,
    },
    {
      id: 16,
      todo: 'Learn the secrets of alchemy',
      completed: true,
      userId: 50,
    },
    {
      id: 17,
      todo: 'Seek the fabled city of gold',
      completed: false,
      userId: 20,
    },
    {
      id: 18,
      todo: 'Help the elves defend their homeland',
      completed: true,
      userId: 43,
    },
    {
      id: 19,
      todo: 'Embark on a quest for immortality',
      completed: false,
      userId: 14,
    },
    {
      id: 20,
      todo: 'Consult the ancient oracle for wisdom',
      completed: false,
      userId: 1,
    },
    {
      id: 21,
      todo: 'Study the ancient runes',
      completed: true,
      userId: 33,
    },
    {
      id: 22,
      todo: 'Protect the sacred grove from desecration',
      completed: false,
      userId: 21,
    },
    {
      id: 23,
      todo: 'Befriend the mysterious creatures of the forest',
      completed: false,
      userId: 3,
    },
    {
      id: 24,
      todo: 'Restore balance to the elemental planes',
      completed: true,
      userId: 19,
    },
    {
      id: 25,
      todo: 'Learn the lost art of teleportation',
      completed: false,
      userId: 11,
    },
    {
      id: 26,
      todo: 'Challenge the champions of the arena',
      completed: true,
      userId: 30,
    },
    {
      id: 27,
      todo: 'Discover the truth behind the ancient legend',
      completed: false,
      userId: 46,
    },
    {
      id: 28,
      todo: 'Forge an alliance with the dwarven clans',
      completed: true,
      userId: 29,
    },
    {
      id: 29,
      todo: 'Study the forbidden grimoires',
      completed: false,
      userId: 25,
    },
    {
      id: 30,
      todo: 'Protect the realm from the dark forces',
      completed: true,
      userId: 38,
    },
    {
      id: 31,
      todo: 'Embark on a pilgrimage to the sacred shrine',
      completed: false,
      userId: 45,
    },
    {
      id: 32,
      todo: "Navigate the treacherous waters of the sea serpent's domain",
      completed: false,
      userId: 37,
    },
    {
      id: 33,
      todo: 'Unlock the secrets of the ancient temple',
      completed: true,
      userId: 48,
    },
    {
      id: 34,
      todo: 'Join the ranks of the elite mage guild',
      completed: true,
      userId: 5,
    },
    {
      id: 35,
      todo: 'Explore the ruins of the fallen kingdom',
      completed: false,
      userId: 15,
    },
    {
      id: 36,
      todo: 'Embark on a journey to find the lost civilization',
      completed: true,
      userId: 42,
    },
    {
      id: 37,
      todo: 'Unlock the power of the ancient relics',
      completed: false,
      userId: 17,
    },
    {
      id: 38,
      todo: 'Rescue the captured mystical creatures',
      completed: true,
      userId: 22,
    },
    {
      id: 39,
      todo: 'Learn the ways of the shadow assassin',
      completed: true,
      userId: 31,
    },
    {
      id: 40,
      todo: 'Consult the celestial beings for guidance',
      completed: false,
      userId: 9,
    },
    {
      id: 41,
      todo: 'Embark on a quest to tame the wild dragon',
      completed: false,
      userId: 18,
    },
    {
      id: 42,
      todo: 'Discover the lost city of Atlantis',
      completed: false,
      userId: 27,
    },
    {
      id: 43,
      todo: 'Train with the legendary phoenix knights',
      completed: true,
      userId: 31,
    },
    {
      id: 44,
      todo: 'Uncover the mysteries of the enchanted forest',
      completed: true,
      userId: 14,
    },
    {
      id: 45,
      todo: 'Seek the wisdom of the ancient tree spirits',
      completed: false,
      userId: 3,
    },
    {
      id: 46,
      todo: 'Defeat the dark warlock threatening the realm',
      completed: false,
      userId: 6,
    },
    {
      id: 47,
      todo: 'Protect the endangered mythical creatures',
      completed: true,
      userId: 37,
    },
    {
      id: 48,
      todo: 'Find the legendary horn of plenty',
      completed: true,
      userId: 27,
    },
    {
      id: 49,
      todo: 'Navigate the treacherous paths of the mountain trolls',
      completed: false,
      userId: 11,
    },
    {
      id: 50,
      todo: 'Embark on a quest to save the elven kingdom',
      completed: true,
      userId: 35,
    },
    {
      id: 51,
      todo: 'Study the ancient scrolls of prophecy',
      completed: false,
      userId: 4,
    },
    {
      id: 52,
      todo: 'Find the lost city of El Dorado',
      completed: true,
      userId: 33,
    },
    {
      id: 53,
      todo: 'Consult the wise old sage for guidance',
      completed: false,
      userId: 44,
    },
    {
      id: 54,
      todo: 'Uncover the secret society of the arcane',
      completed: true,
      userId: 20,
    },
    {
      id: 55,
      todo: 'Defend the kingdom from the curse of the necromancer',
      completed: false,
      userId: 42,
    },
    {
      id: 56,
      todo: 'Seek the lost temple of the moon goddess',
      completed: true,
      userId: 30,
    },
    {
      id: 57,
      todo: 'Train with the legendary dragon riders',
      completed: true,
      userId: 19,
    },
    {
      id: 58,
      todo: 'Embark on a quest to find the fountain of youth',
      completed: false,
      userId: 8,
    },
    {
      id: 59,
      todo: 'Discover the truth behind the mysterious disappearances',
      completed: false,
      userId: 15,
    },
    {
      id: 60,
      todo: 'Protect the sacred relics from falling into the wrong hands',
      completed: true,
      userId: 41,
    },
    {
      id: 61,
      todo: 'Defeat the ancient guardians of the forbidden temple',
      completed: true,
      userId: 23,
    },
    {
      id: 62,
      todo: 'Uncover the hidden chambers of the lost pyramid',
      completed: false,
      userId: 5,
    },
    {
      id: 63,
      todo: 'Navigate the perilous journey through the abyssal plains',
      completed: false,
      userId: 2,
    },
    {
      id: 64,
      todo: 'Seek the blessing of the celestial beings',
      completed: true,
      userId: 24,
    },
    {
      id: 65,
      todo: 'Explore the depths of the underwater kingdom',
      completed: true,
      userId: 1,
    },
    {
      id: 66,
      todo: 'Train with the ancient monks of the mountain temple',
      completed: false,
      userId: 50,
    },
    {
      id: 67,
      todo: 'Retrieve the lost amulet of power',
      completed: false,
      userId: 30,
    },
    {
      id: 68,
      todo: "Find the legendary griffin's nest",
      completed: true,
      userId: 6,
    },
    {
      id: 69,
      todo: 'Protect the innocent villagers from the marauding bandits',
      completed: false,
      userId: 28,
    },
    {
      id: 70,
      todo: 'Uncover the truth behind the cursed ruins',
      completed: true,
      userId: 39,
    },
    {
      id: 71,
      todo: 'Seek the ancient artifacts scattered across the land',
      completed: true,
      userId: 16,
    },
    {
      id: 72,
      todo: 'Train with the master archers of the elven forest',
      completed: false,
      userId: 48,
    },
    {
      id: 73,
      todo: 'Embark on a journey to the realm of the gods',
      completed: false,
      userId: 26,
    },
    {
      id: 74,
      todo: 'Learn the secrets of the shadow realm',
      completed: true,
      userId: 7,
    },
    {
      id: 75,
      todo: 'Defend the kingdom from the wrath of the elemental titans',
      completed: true,
      userId: 50,
    },
    {
      id: 76,
      todo: 'Seek the ancient library of forbidden knowledge',
      completed: false,
      userId: 43,
    },
    {
      id: 77,
      todo: 'Discover the lost city of Shangri-La',
      completed: false,
      userId: 17,
    },
    {
      id: 78,
      todo: 'Train with the legendary swordsmen of the eastern empire',
      completed: true,
      userId: 34,
    },
    {
      id: 79,
      todo: 'Navigate the treacherous jungle to find the hidden temple',
      completed: true,
      userId: 4,
    },
    {
      id: 80,
      todo: 'Seek the blessing of the ancient forest spirits',
      completed: false,
      userId: 25,
    },
    {
      id: 81,
      todo: 'Learn the art of shape-shifting from the druid elders',
      completed: false,
      userId: 40,
    },
    {
      id: 82,
      todo: 'Defend the realm from the invasion of the dark elves',
      completed: false,
      userId: 33,
    },
    {
      id: 83,
      todo: 'Seek the guidance of the starry seer',
      completed: true,
      userId: 35,
    },
    {
      id: 84,
      todo: 'Embark on a quest to find the legendary phoenix',
      completed: true,
      userId: 7,
    },
    {
      id: 85,
      todo: 'Discover the hidden sanctuary of the ice dragons',
      completed: false,
      userId: 32,
    },
    {
      id: 86,
      todo: 'Train with the elite guardians of the celestial palace',
      completed: true,
      userId: 1,
    },
    {
      id: 87,
      todo: 'Retrieve the lost crown of the ancient kings',
      completed: true,
      userId: 43,
    },
    {
      id: 88,
      todo: 'Uncover the truth behind the cursed lands',
      completed: false,
      userId: 13,
    },
    {
      id: 89,
      todo: 'Seek the lost city of the sunken empire',
      completed: false,
      userId: 27,
    },
    {
      id: 90,
      todo: 'Defend the village from the wrath of the fire giants',
      completed: false,
      userId: 12,
    },
    {
      id: 91,
      todo: 'Embark on a journey to the land of eternal winter',
      completed: false,
      userId: 15,
    },
    {
      id: 92,
      todo: 'Train with the ancient warriors of the northern tribes',
      completed: true,
      userId: 46,
    },
    {
      id: 93,
      todo: 'Seek the lost temple of the sun god',
      completed: true,
      userId: 35,
    },
    {
      id: 94,
      todo: 'Discover the hidden chamber of the time keepers',
      completed: false,
      userId: 26,
    },
    {
      id: 95,
      todo: 'Defend the realm from the invasion of the shadow demons',
      completed: false,
      userId: 21,
    },
    {
      id: 96,
      todo: 'Seek the ancient city of the sky dwellers',
      completed: true,
      userId: 13,
    },
    {
      id: 97,
      todo: 'Train with the legendary guardians of the crystal kingdom',
      completed: true,
      userId: 34,
    },
    {
      id: 98,
      todo: 'Retrieve the lost scepter of the high king',
      completed: false,
      userId: 11,
    },
    {
      id: 99,
      todo: 'Embark on a quest to find the mythical land of Avalon',
      completed: true,
      userId: 47,
    },
    {
      id: 100,
      todo: 'Discover the secret passageway to the underworld',
      completed: true,
      userId: 36,
    },
    {
      id: 101,
      todo: 'Seek the blessing of the celestial dragons',
      completed: false,
      userId: 45,
    },
    {
      id: 102,
      todo: 'Train with the elite guards of the celestial palace',
      completed: false,
      userId: 23,
    },
    {
      id: 103,
      todo: 'Retrieve the lost horn of the ancient giants',
      completed: true,
      userId: 31,
    },
    {
      id: 104,
      todo: 'Embark on a journey to the land of the rising sun',
      completed: true,
      userId: 40,
    },
    {
      id: 105,
      todo: 'Discover the lost city of the golden phoenix',
      completed: false,
      userId: 18,
    },
    {
      id: 106,
      todo: 'Defend the village from the invasion of the goblin horde',
      completed: true,
      userId: 21,
    },
    {
      id: 107,
      todo: 'Seek the wisdom of the ancient dragon elders',
      completed: true,
      userId: 2,
    },
    {
      id: 108,
      todo: 'Train with the legendary guardians of the divine realm',
      completed: false,
      userId: 41,
    },
    {
      id: 109,
      todo: 'Retrieve the lost tome of forbidden magic',
      completed: false,
      userId: 14,
    },
    {
      id: 110,
      todo: 'Embark on a quest to find the legendary phoenix egg',
      completed: true,
      userId: 16,
    },
    {
      id: 111,
      todo: 'Discover the hidden sanctuary of the ancient sea dragons',
      completed: false,
      userId: 48,
    },
    {
      id: 112,
      todo: 'Defend the kingdom from the wrath of the ancient titan',
      completed: true,
      userId: 9,
    },
    {
      id: 113,
      todo: 'Seek the lost city of the golden sands',
      completed: false,
      userId: 10,
    },
    {
      id: 114,
      todo: 'Train with the elite guards of the celestial city',
      completed: true,
      userId: 41,
    },
    {
      id: 115,
      todo: 'Retrieve the lost talisman of the ancient druids',
      completed: false,
      userId: 6,
    },
    {
      id: 116,
      todo: 'Embark on a journey to the land of eternal spring',
      completed: false,
      userId: 39,
    },
    {
      id: 117,
      todo: 'Discover the lost city of the silver serpents',
      completed: true,
      userId: 14,
    },
    {
      id: 118,
      todo: 'Defend the village from the invasion of the dark sorcerers',
      completed: true,
      userId: 28,
    },
    {
      id: 119,
      todo: 'Seek the blessing of the celestial phoenix',
      completed: false,
      userId: 19,
    },
    {
      id: 120,
      todo: 'Train with the legendary warriors of the celestial realm',
      completed: false,
      userId: 29,
    },
    {
      id: 121,
      todo: 'Retrieve the lost crystal of the ancient seers',
      completed: false,
      userId: 25,
    },
    {
      id: 122,
      todo: 'Embark on a quest to find the mythical land of Avalon',
      completed: true,
      userId: 28,
    },
    {
      id: 123,
      todo: 'Discover the hidden sanctuary of the ancient forest spirits',
      completed: true,
      userId: 9,
    },
    {
      id: 124,
      todo: 'Defend the kingdom from the invasion of the dark dragons',
      completed: false,
      userId: 44,
    },
    {
      id: 125,
      todo: 'Seek the lost city of the ancient sages',
      completed: true,
      userId: 45,
    },
    {
      id: 126,
      todo: 'Train with the elite guardians of the celestial mountain',
      completed: true,
      userId: 14,
    },
    {
      id: 127,
      todo: 'Retrieve the lost crown of the ancient kings',
      completed: true,
      userId: 25,
    },
    {
      id: 128,
      todo: 'Embark on a journey to the land of eternal night',
      completed: false,
      userId: 29,
    },
    {
      id: 129,
      todo: 'Discover the lost city of the silver moon',
      completed: false,
      userId: 27,
    },
    {
      id: 130,
      todo: 'Defend the village from the invasion of the shadow warriors',
      completed: false,
      userId: 1,
    },
    {
      id: 131,
      todo: 'Seek the blessing of the celestial guardians',
      completed: true,
      userId: 34,
    },
    {
      id: 132,
      todo: 'Train with the legendary warriors of the celestial kingdom',
      completed: false,
      userId: 32,
    },
    {
      id: 133,
      todo: 'Retrieve the lost crystal of the ancient seers',
      completed: false,
      userId: 47,
    },
    {
      id: 134,
      todo: 'Embark on a quest to find the mythical land of Avalon',
      completed: true,
      userId: 6,
    },
    {
      id: 135,
      todo: 'Discover the hidden sanctuary of the ancient forest spirits',
      completed: false,
      userId: 40,
    },
    {
      id: 136,
      todo: 'Defend the kingdom from the invasion of the dark dragons',
      completed: true,
      userId: 37,
    },
    {
      id: 137,
      todo: 'Seek the lost city of the ancient sages',
      completed: true,
      userId: 26,
    },
    {
      id: 138,
      todo: 'Train with the elite guardians of the celestial mountain',
      completed: false,
      userId: 2,
    },
    {
      id: 139,
      todo: 'Retrieve the lost crown of the ancient kings',
      completed: false,
      userId: 16,
    },
    {
      id: 140,
      todo: 'Embark on a journey to the land of eternal night',
      completed: true,
      userId: 12,
    },
    {
      id: 141,
      todo: 'Discover the lost city of the silver moon',
      completed: true,
      userId: 48,
    },
    {
      id: 142,
      todo: 'Defend the village from the invasion of the shadow warriors',
      completed: false,
      userId: 49,
    },
    {
      id: 143,
      todo: 'Seek the blessing of the celestial guardians',
      completed: false,
      userId: 17,
    },
    {
      id: 144,
      todo: 'Train with the legendary warriors of the celestial kingdom',
      completed: false,
      userId: 45,
    },
    {
      id: 145,
      todo: 'Retrieve the lost crystal of the ancient seers',
      completed: false,
      userId: 1,
    },
    {
      id: 146,
      todo: 'Embark on a quest to find the mythical land of Avalon',
      completed: true,
      userId: 39,
    },
    {
      id: 147,
      todo: 'Discover the hidden sanctuary of the ancient forest spirits',
      completed: false,
      userId: 47,
    },
    {
      id: 148,
      todo: 'Defend the kingdom from the invasion of the dark dragons',
      completed: true,
      userId: 20,
    },
    {
      id: 149,
      todo: 'Seek the lost city of the ancient sages',
      completed: false,
      userId: 44,
    },
    {
      id: 150,
      todo: 'Train with the elite guardians of the celestial mountain',
      completed: false,
      userId: 15,
    },
  ];

  constructor() {}

  accomplish(todo: iTodos) {
    todo.completed = !todo.completed;
  }
}
