export const environment = {
  lansUrl:'http://localhost:8080/api/lans',
  newLansUrl:'http://localhost:8080/api/lans/available',
  boardsUrl:'http://localhost:8080/api/boards',
  newBoardsUrl:'http://localhost:8080/api/boards/available',
  newBoardsBookingUrl:'http://localhost:8080/api/bookings/boardbookingclose',
  openBoardsUrl:'http://localhost:8080/api/bookings/openbookings',
  // openBoardsBookingUrl:'http://localhost:8080/api/bookings/boardbookingopen',
  lanBookingUrl: 'http://localhost:8080/api/bookings/lanbooking',
  bookingsByDateUrl: 'http://localhost:8080/api/bookings/bookingsbydate',
  bookingsById: 'http://localhost:8080/api/bookings/bookingbyid',
  boardsBySeats: 'http://localhost:8080/api/boards/byseats',
  loginUrl: 'http://localhost:8080/auth/login',
  bookingsUrl: 'http://localhost:8080/api/bookings',
  deleteBookingUrl: 'http://localhost:8080/api/bookings',
  deleteStationUrl: 'http://localhost:8080/api',
  updateBoardUrl: 'http://localhost:8080/api/boards',
  postStationUrl: 'http://localhost:8080/api/save',
  editBookingUrl:'http://localhost:8080/api/bookings'
};
